### ISSUE TITLE
Problem with adding object properties and object properties statements in ontologies

### ISSUE THREAD

**Issue by hibahnaini** [openflexo-team/openflexo-core#22]
![image](https://github.com/user-attachments/assets/fd766a8a-8e18-45f3-8524-b76a57798c0f)

Problem with the "object" property in the AddObjectPropertyStatement method.
Also the AddObjectProperty method is not implemented.
[ontology-test.prj.zip](https://github.com/user-attachments/files/17574255/ontology-test.prj.zip)

**Comment by sylvain-openflexo** [comment]
Added missing @FMLAttribute in getObject(...)
